### ISSUE TITLE
Detect Vue 3

### ISSUE THREAD

**Issue by Atinux** [nuxt-company/vue-telemetry-analyzer#11]
### Is your feature request related to a problem? Please describe.

We cannot detect Vue 3 at the moment.

### Describe the solution you'd like

Detecting Vue 3 websites, examples:
- jaysonu.com
- icones.netlify.app

### Additional context

- use `window.__VUE__` to detect whether Vue 3 is on the page (will be true instead of the version number, since it's technically possible to have multiple apps using different versions of Vue 3 on the same page)
- Once we detect Vue 3, we can do `document.querySelectorAll('[data-vue-app]')` to get all the app container elements
- On each app container element, the app instance is exposed as `__vue_app__`
- The app instance exposes `.version` and `.config.devtools`

**Comment by damianof** [comment]
👍

**Comment by web2033** [comment]
Maybe ask the Vue team whether they could add some hints to the source code that would make version detection easier?

**Comment by antfu** [comment]
Just tried on Icones, `window.__VUE__` does not exist. However, you can access the version by 

```js
document.querySelectorAll('[data-v-app]')?.[0]?.__vue_app__?.version
```

**Comment by Atinux** [comment]
Thank you @antfu <3

Do you have any idea also regarding the Vue 3 plugins detection?

**Comment by antfu** [comment]
AFAIN,

Vue Router

```js
document.querySelectorAll('[data-v-app]')?.[0]?.__vue_app__?.config?.globalProperties?.$router
```

vue-i18n (a bit tricky)

```js
Object.getOwnPropertySymbols(
  document.querySelectorAll('[data-v-app]')?.[0]?.__vue_app__?._context?.provides || {}
).some(i => i.toString() === 'Symbol(vue-i18n)')
```

hope it helps

**Comment by Atinux** [comment]
Thanks @antfu it does help!
