### ISSUE TITLE
Improve nuxt detection

### ISSUE THREAD

**Issue by pimlie** [nuxt-company/vue-telemetry-analyzer#12]
### Is your feature request related to a problem? Please describe.

Checking `window.$nuxt` is unreliable as users can change the `globalName`

### Describe the solution you'd like

Check the nuxt client's inner nuxt property

### Describe alternatives you've considered

na

### Additional context

This should work `el.__vue__.nuxt` and otherwise `el.__vue__.$root.nuxt`

**Comment by Atinux** [comment]
Thank you @pimlie 

Add better detection here: https://github.com/nuxt-company/vue-telemetry-analyzer/commit/b9d94da6fa0e7ce4d2deed7934ea52dc5086fbb1
