### ISSUE TITLE
Problem when trying to lookup with a .me domain

### ISSUE THREAD

**Issue by alfonsobries** [nuxt-company/vue-telemetry-analyzer#18]
### Version

Look up form in the home page

### Reproduction Link

https://vuetelemetry.com/

### Steps to reproduce
go to the lookup form in https://vuetelemetry.com/and try to add the site https://www.dona.me/

### What is Expected?
To be added to the list

### What is actually happening?

Its redirecting to `https://vuetelemetry.com/explore/dona-me` who makes an ajax request with a 404 error and throws 
`Uncaught SyntaxError: Unexpected token '<'`

![image](https://user-images.githubusercontent.com/17262776/92642939-949c8500-f2a6-11ea-9cb9-e2aaf2714fd7.png)

**Comment by Atinux** [comment]
It's fixed: https://vuetelemetry.com/explore/dona-me

Thank you for reporting @alfonsobries
