### ISSUE TITLE
Official Website retrieves Spawn ENOMEM error.

### ISSUE THREAD

**Issue by x-N0** [nuxt-company/vue-telemetry-analyzer#23]
### Version

vue-telemetry-analyzer: Web(latest?)

### Reproduction Image
![imagen](https://user-images.githubusercontent.com/51316342/93096196-18bd8680-f672-11ea-8659-ba469cd2d85b.png)

### Steps to reproduce
Looks like the error comes from any website that is not into the db and don't use Vue.
Open the web, search for netamorphosis.com.

### What is Expected?
Spawn Enomem Nodejs Error.

### What is actually happening?
I think Nodejs runs out of memory.
Found about it here: [SlackOverflow Nodejs catch Enomem](https://stackoverflow.com/questions/26193654/node-js-catch-enomem-error-thrown-after-spawn)

**Comment by Atinux** [comment]
Should be fixed now :)

**Comment by divine** [comment]
Hi @Atinux 

There are still errors:

`{"message":"A timeout occured, please try again later.","statusCode":408}`

Thanks!

**Comment by Atinux** [comment]
Can you try again @divine ?

**Comment by divine** [comment]
@Atinux I have just tried now it says "Navigation timeout of 30000 ms exceeded".

**Comment by Atinux** [comment]
What's the website? @divine

**Comment by divine** [comment]
@Atinux it's a mail.tm.

New error is "Vue is not detected on https://mail.tm (saved scan)", however extension does detect everything correctly.

**Comment by frontender-ua** [comment]
same error here with message "Navigation timeout of 30000 ms exceeded"
website https://production.lorashen.ua
vuetelemetry plugin for chrome show all ok

<img width="592" alt="Screenshot 2020-11-16 at 01 47 42" src="https://user-images.githubusercontent.com/13487285/99200398-bdad2a80-27ad-11eb-82e1-295321a24b83.png">

**Comment by nethriis** [comment]
same issue this is not fixed
