### ISSUE TITLE
Certain website functions stop working - Chromium Edge

### ISSUE THREAD

**Issue by arpadgabor** [nuxt-company/vue-telemetry-analyzer#25]
### Version

vue-telemetry-analyzer: 1.4.0

### Reproduction Link

https://blog.google/

### Steps to reproduce

Press on menu items on the website. Nothing works except for the links.

### What is Expected?

The menu items to work. Tried uninstalling the extension and then it worked just fine.

### What is actually happening?

![image](https://user-images.githubusercontent.com/9270494/94728940-aafba500-0369-11eb-96a8-ad9983194997.png)

**Comment by Atinux** [comment]
Should be fixed with latest version of the extension.
