### ISSUE TITLE
Blur NSFW Content/Site images

### ISSUE THREAD

**Issue by TheLearneer** [nuxt-company/vue-telemetry-analyzer#26]
### Is your feature request related to a problem? Please describe.
I was just going through the site and exploring showcase section when I saw a NSFW site listed and also NSFW images popping out.

### Describe the solution you'd like
Maybe add some blur to images when the website includes NSFW stuffs. Not sure how it can be done, but I suppose NSFW stuffs are not to be displayed by default ??

### Additional context
Found this particular one hanime.tv while going through Nuxt, Vuetify sorted by popularity.

**Comment by Atinux** [comment]
Fixed, we actually blur image and add 18+ filter.

Looks like this one bypassed our adult content filter. Thank you for reporting @TheLearneer 

Context: https://vuetelemetry.com/explore/hanime-tv

**Comment by TheLearneer** [comment]
@Atinux Thanks for fixing it, but seems like there are few more that have bypassed the adult content filer.

Names: shemale.move and new.lewd.ninja

**Comment by Atinux** [comment]
Will fix thanks
